### ISSUE TITLE
Clock pin?

### ISSUE THREAD

**Issue by shingtaklam1324** [MMjoy/mmjoy_en#2]
On the datasheet of the 74HC135, pin2 is the clock pin, which on the PCB drawing is shown as SCK. Is there a built in SCK in MMJOY or do I have to build a clock?

**Comment by kirilscherbach** [comment]
Could you please give me a link to the PCB drawing in the repo?

**Comment by shingtaklam1324** [comment]
[Here](https://github.com/MMjoy/mmjoy_en/blob/master/PCB/MMJoy2_74HC165.lay6)

The 16bit drawing
